apiVersion: batch/v1
kind: CronJob
metadata:
  name: ping-cron-job
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: centos
              image: centos:8
              command: ["ping", "ya.ru", "-c", "5"]
          restartPolicy: Never
      backoffLimit: 3
      ttlSecondsAfterFinished: 120