apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-v16
data:
  index.html: |-
    nginx-v16

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-blue
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
      role: blue
  template:
    metadata:
      labels:
        app: nginx
        role: blue
    spec:
      containers:
        - name: nginx
          image: nginx:1.16.1
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /usr/share/nginx/html/index.html
              name: index-html
              subPath: index.html
      volumes:
        - name: index-html
          configMap:
            name: nginx-v16