apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-v14
data:
  index.html: |-
    nginx-v14
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-green
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
      role: green
  template:
    metadata:
      labels:
        app: nginx
        role: green
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /usr/share/nginx/html/index.html
              name: index-html
              subPath: index.html
      volumes:
        - name: index-html
          configMap:
            name: nginx-v14