apiVersion: v1
kind: Service
metadata:
  name: nginx-green
spec:
  selector:
    app: nginx
    role: green
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 80