apiVersion: v1
kind: Service
metadata:
  name: nginx-blue
spec:
  selector:
    app: nginx
    role: blue
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 80