apiVersion: v1
kind: Secret
metadata:
  name: secret-env
type: Opaque
stringData:
  username: username
  password: password
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: centos
  labels:
    app: centos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: centos
  template:
    metadata:
      labels:
        app: centos
    spec:
      containers:
        - name: centos
          image: centos:8
          command: ["/bin/sleep", "3650d"]
          env:
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: secret-env
                  key: username
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-env
                  key: password