#
#  Run "kubectl create secret generic secret-file --from-file=secret.properties" for creating secret
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: centos
  labels:
    app: centos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: centos
  template:
    metadata:
      labels:
        app: centos
    spec:
      containers:
        - name: centos
          image: centos:8
          command: ["/bin/sleep", "3650d"]
          volumeMounts:
            - mountPath: /tmp/secret.properties
              subPath: secret.properties
              name: secret-file
      volumes:
        - name: secret-file
          secret:
            secretName: secret-file