apiVersion: v1
kind: ConfigMap
metadata:
  name: config-env
  namespace: default
data:
  ENV_PARAM1: param1_value
  ENV_PARAM2: param2_value
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: centos
  labels:
    app: centos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: centos
  template:
    metadata:
      labels:
        app: centos
    spec:
      containers:
        - name: centos
          image: centos:8
          command: ["/bin/sleep", "3650d"]
          env:
            - name: ENV_PARAM1
              valueFrom:
                configMapKeyRef:
                  name: config-env
                  key: ENV_PARAM1
            - name: ENV_PARAM2
              valueFrom:
                configMapKeyRef:
                  name: config-env
                  key: ENV_PARAM2